version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: demoxv_sso_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: demoxv_admin
      POSTGRES_PASSWORD: demoxv_secret_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demoxv_admin -d sso_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
